### PR TITLE
Fix memory leaks in compute_vhacd

### LINKED ISSUE #7: Memory leak in compute_vhacd
To reproduce

1. download [featuretype.STL](https://github.com/mikedh/trimesh/blob/ffe3c35c32b318012aadd797a6a38e8d8d793157/models/featuretype.STL)
2. run script below
3. after 30 seconds one can clearly see that process memory keeps growing

```
1198.16MB
1217.91MB
1231.41MB
1242.79MB
1257.89MB
```

```python
import os
import psutil
import trimesh

m = trimesh.load_mesh("./featuretype.STL")


def get_memory_usage():
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    return mem_info.rss / (1024 * 1024)


while True:
    m.convex_decomposition()
    print(f"{get_memory_usage():.2f}MB")
```

Potential fix

```diff
diff --git a/src/vhacdx/main.cpp b/src/vhacdx/main.cpp
index 2811253..ab2869f 100644
--- a/src/vhacdx/main.cpp
+++ b/src/vhacdx/main.cpp
@@ -111,7 +111,6 @@ compute_vhacd(py::array_t<double> points, py::array_t<uint32_t> faces,
         ptr_res_vertices[3 * j + 2] = pos.mZ;
       }

-      const uint32_t num_v = 3;
       for (uint32_t j = 0; j < ch.m_triangles.size(); j++) {
         uint32_t i1 = ch.m_triangles[j].mI0;
         uint32_t i2 = ch.m_triangles[j].mI1;
@@ -131,6 +130,9 @@ compute_vhacd(py::array_t<double> points, py::array_t<uint32_t> faces,
       res.emplace_back(std::move(res_vertices), std::move(res_faces));
     }
   }
+
+  iface->Release();
+  delete[] triangles;
   return res;
 }
```

### PR DESCRIPTION
**Pull request by r7vme**
Fixes https://github.com/trimesh/vhacdx/issues/7

### CODE REVIEW

File: src/vhacdx/main.cpp [hunk 1]
```diff
@@ -111,7 +111,6 @@ compute_vhacd(py::array_t<double> points, py::array_t<uint32_t> faces,
         ptr_res_vertices[3 * j + 2] = pos.mZ;
       }
 
-      const uint32_t num_v = 3;
```
Comment (r7vme) [inline src/vhacdx/main.cpp:114]: not related to mem leak, just unused variable

**Comment by r7vme** [comment]
@mikedh can you please review this PR?

**Comment by mikedh** [comment]
Thanks for the fix!!
